baseURL = "https://www.mangobrain.co.uk/"
languageCode = "en-GB"
title = "Mangobrain"
disableKinds = ["taxonomy", "taxonomyTerm", "category", "sitemap", "RSS", "section"]

[markup]
    [markup.highlight]
        noClasses = false
